global:
  scrape_interval: 35s

scrape_configs:
  - job_name: 'kafka-producer'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'kafka-consumer'
    static_configs:
      - targets: ['localhost:8001']
